version: "3.3"
services:
  app:
    container_name: app
    image: app
    build:
      context: ./
      dockerfile: app.Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - redis
      - db
    links:
      - redis
      - db
  redis:
    container_name: redis
    image: redis
    ports:
      - 6379:6379
  db:
    container_name: db
    image: db
    build:
      context: ./
      dockerfile: db.Dockerfile
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres